export const data = {
  retailCategory: [
    "Apparel and Fashion Retail",
    "Electronics and Appliances Retail",
    "Grocery and Supermarkets",
    "Home and Furniture Stores",
    "Automotive Retail",
    "Pharmacy and Health Stores",
    "Beauty and Cosmetics Stores",
    "Sports and Outdoor Retail",
    "Books and Stationery Stores",
    "Toy Stores",
    "DIY and Home Improvement Stores",
    "Specialty Stores",
    "Discount Stores",
    "Online Retail",
    "Secondhand and Thrift Stores",
    "Jewelry Stores",
    "Art and Craft Stores",
    "Liquor Stores",
    "Convenience Stores",
  ],
  cameraNetwork: ["Analog Camera", "IP Camera"],
  employeeNum: ["1~5", "6~20", "21~50", "50+"],
};
